trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'manoj-portfolio'

steps:
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: 'manoj-acr-connection'
    repository: 'manoj-portfolio'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest