trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    node -v
    npm -v
    npm install
    npm run build
  displayName: Build Angular App